# Generated by Django 4.1.5 on 2023-01-24 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='word',
            name='text',
            field=models.EmailField(error_messages={'unique': 'The Geeks Field you entered is not unique.'}, max_length=255, unique=True),
        ),
    ]
